# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeoutoption',
            name='timeout',
            field=models.IntegerField(),
        ),
    ]
